spring.application.name=hireflow-backend
# Application name
spring.application.name=hireflow-backend

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/hireflow
spring.datasource.username=root
spring.datasource.password=gauri1980

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080